apiVersion: v1
kind: ReplicationController
metadata: 
  name: phpinfo-rc
spec:
  replicas: 2
  selector: 
    app: phpinfo
    branch: santander
  template:
    metadata: 
      labels: 
        app: phpinfo
        branch: santander
    spec: 
      containers:
        - 
          args: 
            - -f 
            - src/index.php
            - -S 
            - 0.0.0.0:8080
          command:
            - /usr/bin/php
          env: 
            - 
              name: author
              value: PaulaRestrepo
            - 
              name: JAVA_HOME
              value: /var/lib/java
          image: paularestrepo/phpinfo:santander
          # imagePullPolicy: Always
          name: phpinfo-container
          ports: 
            -  
              containerPort: 8080
              protocol: TCP
          volumeMounts: 
            - 
              mountPath: /src/index.php
              name: phpinfo-volume
              readOnly: true
              subPath: index.php
      initContainers:
        - 
          args: 
            - -c 
            - test -f index.php && wget https://raw.githubusercontent.com/isper79/phpinfo/santander/src/index.php 
          command:
            - /bin/sh
          env: 
            - 
              name: author
              value: PaulaRestrepo
            - 
              name: JAVA_HOME
              value: /var/lib/java
          image: library/busybox:latest
          # imagePullPolicy: Always
          name: phpinfo-initcontainer
          volumeMounts: 
            - 
              mountPath: /src/
              name: phpinfo-volume
              readOnly: false
          workingDir: /src/
      volumes: 
        - 
          persistentVolumeClaim: 
            claimName: phpinfo-pvc
            readOnly: false            
          name: phpinfo-volume
---
apiVersion: v1
kind: Service
metadata: 
  name: phpinfo-svc
spec:
  clusterIP: ''
  ports: 
    - 
      port: 80
      protocol: TCP 
      targetPort: 8080
  selector:
    app: phpinfo
    branch: santander
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumenClaim
metadata: 
  name: phpinfo-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    limits:
      storage: 1M
    request:
      storage: 1M
  storageClassName: gp2
