apiVersion: v1
kind: ReplicationController
metadata: 
  name: phpinfo-rcs-optimizado
spec:
  replicas: 2
  selector: 
    app: phpinfo
    branch: santander-optimizado
  template:
    metadata: 
      labels: 
        app: phpinfo
        branch: santander-optimizado
    spec: 
      containers:
        - 
          args: 
            - -f 
            - src/index.php
            - -S 
            - 0.0.0.0:8080
          command:
            - /usr/bin/php
          env: 
            - 
              name: author
              value: PaulaRestrepoAlonso
            - 
              name: JAVA_HOME
              value: /var/lib/java
          image: paularestrepo/phpinfo:santander-optimizado
          name: phpinfo-container
          ports: 
            -  
              containerPort: 8080
              protocol: TCP
          volumeMounts: 
            - 
              mountPath: /src/index.php
              name: phpinfo-volume
              readOnly: true
              subPath: index.php
      volumes: 
        - 
          configMap: 
            defaultMode: 0400
            items: 
              - 
                key: index.php
                mode: 0400
                path: index.php
            name: phpinfo-cm
            # kubectl create cm --from-file ./src/index.php phpinfo-cm
          name: phpinfo-volume
